"""
This type stub file was generated by pyright.
"""

def set_feasibility(pop):
    ...

def set_cv(pop, feasbility=...):
    ...

class Evaluator:
    """

    The evaluator class which is used during the algorithm execution to limit the number of evaluations.
    This can be based on convergence, maximum number of evaluations, or other criteria.

    """
    def __init__(self, skip_already_evaluated=..., evaluate_values_of=...) -> None:
        ...
    
    def eval(self, problem, pop, **kwargs):
        """

        This function is used to return the result of one valid evaluation.

        Parameters
        ----------
        problem : class
            The problem which is used to be evaluated
        pop : np.array or Population object
        kwargs : dict
            Additional arguments which might be necessary for the problem to evaluate.

        """
        ...
    


