"""
This type stub file was generated by pyright.
"""

def is_better(_new, _old, eps=...):
    ...

class ReplacementStrategy:
    def do(self, problem, pop, off, return_indices=..., inplace=..., **kwargs):
        ...
    


class ImprovementReplacement(ReplacementStrategy):
    ...


