"""
This type stub file was generated by pyright.
"""

from statsmodels.tools._testing import PytestTester
from .empirical_distribution import ECDF, StepFunction, monotone_fn_inverter
from .edgeworth import ExpandedNormal
from .discrete import genpoisson_p, zigenpoisson, zinegbin, zipoisson

test = PytestTester()
