[tool.poetry]
name = "pyvado"
version = "0.1.0"
description = "A Python layer over Vivado through TCL"
authors = ["Daniele Paletti"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
