[tool.poetry]
name = "pyvado"
version = "0.1.0"
description = "A Python layer over Vivado through TCL"
authors = ["Daniele Paletti"]
license = "Eclipse"
readme = "README.md"
homepage = "https://github.com/DPaletti/pyvado"
repository = "https://github.com/DPaletti/pyvado"
keywords = ["Xilinx", "Vivado", "TCL", "VHDL", "Verilog", "RTL", "Design Space"]

[tool.poetry.dependencies]
python = "^3.8"
pathvalidate = "^2.3.0"
BeautifulSoup4 = "^4.9.1"
lxml = "^4.5.2"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
pyvado = "pyvado.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
