"""
This type stub file was generated by pyright.
"""

from pymoo.problems.many.dtlz import *
from pymoo.problems.many.cdtlz import *
from pymoo.problems.many.dcdtlz import *
from pymoo.problems.many.wfg import *

