"""
This type stub file was generated by pyright.
"""

from pymoo.problems.many.dtlz import DTLZ1, DTLZ2, DTLZ3, DTLZ4

class C1DTLZ1(DTLZ1):
    def __init__(self, n_var=..., n_obj=..., **kwargs) -> None:
        ...
    


class C1DTLZ3(DTLZ3):
    def __init__(self, n_var=..., n_obj=..., r=..., **kwargs) -> None:
        ...
    


class C2DTLZ2(DTLZ2):
    def __init__(self, n_var=..., n_obj=..., r=..., **kwargs) -> None:
        ...
    


class C3DTLZ1(DTLZ1):
    def __init__(self, n_var=..., n_obj=..., **kwargs) -> None:
        ...
    


class C3DTLZ4(DTLZ4):
    def __init__(self, n_var=..., n_obj=..., **kwargs) -> None:
        ...
    


def constraint_c1_linear(f):
    ...

def constraint_c1_spherical(f, r):
    ...

def constraint_c2(f, r):
    ...

def constraint_c3_linear(f):
    ...

def constraint_c3_spherical(f):
    ...

def constraint_c4_cylindrical(f, r):
    ...

