"""
This type stub file was generated by pyright.
"""

class Dominator:
    @staticmethod
    def get_relation(a, b, cva=..., cvb=...):
        ...
    
    @staticmethod
    def calc_domination_matrix_loop(F, G):
        ...
    
    @staticmethod
    def calc_domination_matrix(F, _F=..., epsilon=...):
        """
        if G is None or len(G) == 0:
            constr = np.zeros((F.shape[0], F.shape[0]))
        else:
            # consider the constraint violation
            # CV = Problem.calc_constraint_violation(G)
            # constr = (CV < CV) * 1 + (CV > CV) * -1

            CV = Problem.calc_constraint_violation(G)[:, 0]
            constr = (CV[:, None] < CV) * 1 + (CV[:, None] > CV) * -1
        """
        ...
    


