"""
This type stub file was generated by pyright.
"""

import numpy as np

def randomized_argsort(A, method=..., order=...):
    ...

def quicksort(A):
    ...

if __name__ == '__main__':
    a = np.array([5, 9, 10, 0, 0, 0, 100, - 2])
