"""
This type stub file was generated by pyright.
"""

from antlr4.RuleContext import RuleContext
from antlr4.Token import Token
from antlr4.tree.Tree import ParseTree, ParseTreeListener

ParserRuleContext = None
class ParserRuleContext(RuleContext):
    def __init__(self, parent: ParserRuleContext = ..., invokingStateNumber: int = ...) -> None:
        ...
    
    def copyFrom(self, ctx: ParserRuleContext):
        ...
    
    def enterRule(self, listener: ParseTreeListener):
        ...
    
    def exitRule(self, listener: ParseTreeListener):
        ...
    
    def addChild(self, child: ParseTree):
        ...
    
    def removeLastChild(self):
        ...
    
    def addTokenNode(self, token: Token):
        ...
    
    def addErrorNode(self, badToken: Token):
        ...
    
    def getChild(self, i: int, ttype: type = ...):
        ...
    
    def getChildren(self, predicate=...):
        ...
    
    def getToken(self, ttype: int, i: int):
        ...
    
    def getTokens(self, ttype: int):
        ...
    
    def getTypedRuleContext(self, ctxType: type, i: int):
        ...
    
    def getTypedRuleContexts(self, ctxType: type):
        ...
    
    def getChildCount(self):
        ...
    
    def getSourceInterval(self):
        ...
    


class InterpreterRuleContext(ParserRuleContext):
    def __init__(self, parent: ParserRuleContext, invokingStateNumber: int, ruleIndex: int) -> None:
        ...
    


