"""
This type stub file was generated by pyright.
"""

from antlr4.InputStream import InputStream

class StdinStream(InputStream):
    def __init__(self, encoding: str = ..., errors: str = ...) -> None:
        ...
    


