"""
This type stub file was generated by pyright.
"""

from pymoo.util.reference_direction import ReferenceDirectionFactory

class LayerwiseRieszEnergyReferenceDirectionFactory(ReferenceDirectionFactory):
    def __init__(self, n_dim, partitions, return_as_tuple=..., n_max_iter=..., verbose=..., X=..., **kwargs) -> None:
        ...
    
    def do(self):
        ...
    


def get_points(X, scalings):
    ...

def calc_potential_energy(scalings, X):
    ...

