"""
This type stub file was generated by pyright.
"""

from pymoo.model.problem import Problem

DIFFICULTIES = [(0.25, 0, 0), (0, 0.25, 0), (0, 0, 0.25), (0.25, 0.25, 0.25), (0.5, 0, 0), (0, 0.5, 0), (0, 0, 0.5), (0.5, 0.5, 0.5), (0.75, 0, 0), (0, 0.75, 0), (0, 0, 0.75), (0.75, 0.75, 0.75), (0, 1, 0), (0.5, 1, 0), (0, 1, 0.5), (0.5, 1, 0.5)]
class DASCMOP(Problem):
    def __init__(self, n_obj, n_constr, difficulty, **kwargs) -> None:
        ...
    
    def g1(self, X):
        ...
    
    def g2(self, X):
        ...
    
    def g3(self, X):
        ...
    


class DASCMOP1(DASCMOP):
    def __init__(self, difficulty, **kwargs) -> None:
        ...
    
    def constraints(self, X, f0, f1, g):
        ...
    


class DASCMOP2(DASCMOP1):
    ...


class DASCMOP3(DASCMOP1):
    ...


class DASCMOP4(DASCMOP1):
    ...


class DASCMOP5(DASCMOP1):
    ...


class DASCMOP6(DASCMOP1):
    ...


class DASCMOP7(DASCMOP):
    def __init__(self, difficulty_factors, **kwargs) -> None:
        ...
    
    def constraints(self, X, f0, f1, f2, g):
        ...
    


class DASCMOP8(DASCMOP7):
    def objectives(self, X, g):
        ...
    


class DASCMOP9(DASCMOP8):
    ...


