"""
This type stub file was generated by pyright.
"""

from antlr4.tree.ParseTreePatternMatcher import ParseTreePatternMatcher
from antlr4.tree.Tree import ParseTree

class ParseTreePattern(object):
    def __init__(self, matcher: ParseTreePatternMatcher, pattern: str, patternRuleIndex: int, patternTree: ParseTree) -> None:
        ...
    
    def match(self, tree: ParseTree):
        ...
    
    def matches(self, tree: ParseTree):
        ...
    
    def findAll(self, tree: ParseTree, xpath: str):
        ...
    


