"""
This type stub file was generated by pyright.
"""

from antlr4.atn.ATNConfig import ATNConfig

ATNSimulator = None
class ATNConfigSet(object):
    def __init__(self, fullCtx: bool = ...) -> None:
        ...
    
    def __iter__(self):
        ...
    
    def add(self, config: ATNConfig, mergeCache=...):
        ...
    
    def getOrAdd(self, config: ATNConfig):
        ...
    
    def getStates(self):
        ...
    
    def getPredicates(self):
        ...
    
    def get(self, i: int):
        ...
    
    def optimizeConfigs(self, interpreter: ATNSimulator):
        ...
    
    def addAll(self, coll: list):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __hash__(self) -> int:
        ...
    
    def hashConfigs(self):
        ...
    
    def __len__(self):
        ...
    
    def isEmpty(self):
        ...
    
    def __contains__(self, config):
        ...
    
    def clear(self):
        ...
    
    def setReadonly(self, readonly: bool):
        ...
    
    def __str__(self) -> str:
        ...
    


class OrderedATNConfigSet(ATNConfigSet):
    def __init__(self) -> None:
        ...
    


