"""
This type stub file was generated by pyright.
"""

ATNDeserializationOptions = None
class ATNDeserializationOptions(object):
    defaultOptions = ...
    def __init__(self, copyFrom: ATNDeserializationOptions = ...) -> None:
        ...
    
    def __setattr__(self, key, value):
        ...
    


