"""
This type stub file was generated by pyright.
"""

from enum import Enum
from antlr4.atn.ATNConfigSet import ATNConfigSet

PredictionMode = None
class PredictionMode(Enum):
    SLL = ...
    LL = ...
    LL_EXACT_AMBIG_DETECTION = ...
    @classmethod
    def hasSLLConflictTerminatingPrediction(cls, mode: PredictionMode, configs: ATNConfigSet):
        ...
    
    @classmethod
    def hasConfigInRuleStopState(cls, configs: ATNConfigSet):
        ...
    
    @classmethod
    def allConfigsInRuleStopStates(cls, configs: ATNConfigSet):
        ...
    
    @classmethod
    def resolvesToJustOneViableAlt(cls, altsets: list):
        ...
    
    @classmethod
    def allSubsetsConflict(cls, altsets: list):
        ...
    
    @classmethod
    def hasNonConflictingAltSet(cls, altsets: list):
        ...
    
    @classmethod
    def hasConflictingAltSet(cls, altsets: list):
        ...
    
    @classmethod
    def allSubsetsEqual(cls, altsets: list):
        ...
    
    @classmethod
    def getUniqueAlt(cls, altsets: list):
        ...
    
    @classmethod
    def getAlts(cls, altsets: list):
        ...
    
    @classmethod
    def getConflictingAltSubsets(cls, configs: ATNConfigSet):
        ...
    
    @classmethod
    def getStateToAltMap(cls, configs: ATNConfigSet):
        ...
    
    @classmethod
    def hasStateAssociatedWithOneAlt(cls, configs: ATNConfigSet):
        ...
    
    @classmethod
    def getSingleViableAlt(cls, altsets: list):
        ...
    


