"""
This type stub file was generated by pyright.
"""

from pymoo.algorithms.genetic_algorithm import GeneticAlgorithm
from pymoo.model.survival import Survival

class FitnessSurvival(Survival):
    def __init__(self) -> None:
        ...
    


def comp_by_cv_and_fitness(pop, P, **kwargs):
    ...

class GA(GeneticAlgorithm):
    def __init__(self, pop_size=..., sampling=..., selection=..., crossover=..., mutation=..., survival=..., eliminate_duplicates=..., n_offsprings=..., display=..., **kwargs) -> None:
        """

        Parameters
        ----------
        pop_size : {pop_size}
        sampling : {sampling}
        selection : {selection}
        crossover : {crossover}
        mutation : {mutation}
        eliminate_duplicates : {eliminate_duplicates}
        n_offsprings : {n_offsprings}

        """
        ...
    


