flow = "manual_system_verilog_vivado"

project_root = "cv32e40p/rtl"

target_file = "cv32e40p_core.sv"

task_file = "exploration_files/cv32e40p_exploration_file.csv" # if csv we go points mode, if toml we go space mode

board = "xc7k70tfbv676-1"

clock_port = "clk"

custom_metrics_folder = "custom_metrics"


[metrics]
default = ["Slice LUTs*", "frequency"]
custom=["test_metric", "another_test_metric"]
