flow = "manual_hls_vitis"

project_root = "01-convolution-tutorial/src/"

target_file = "filter2d_hw.cpp"

task_file = "exploration_files/filter_exploration_file.csv"

board = "xc7k70tfbv676-1"

clock_port = "ap_clk" # refers to the clock port of the generated module

custom_metrics_folder = "custom_metrics"

[metrics]
default = ["Slice LUTs*", "frequency"]
custom=["test_metric", "another_test_metric"]

[extra]
[extra.vitis]
project_root = "solution1/syn/verilog"
target_file = "Filter2DKernel.v"
target_clock = 100
target_module = "Filter2DKernel"
