"""
This type stub file was generated by pyright.
"""

from distutils.log import *
from distutils.log import Log as old_Log, _global_log
from numpy.distutils.misc_util import cyan_text, default_text, red_text

class Log(old_Log):
    def good(self, msg, *args):
        """
        If we log WARN messages, log this message as a 'nice' anti-warn
        message.

        """
        ...
    


good = _global_log.good
def set_threshold(level, force=...):
    ...

def get_threshold():
    ...

def set_verbosity(v, force=...):
    ...

_global_color_map = { DEBUG: cyan_text,INFO: default_text,WARN: red_text,ERROR: red_text,FATAL: red_text }
