"""
This type stub file was generated by pyright.
"""

import csv

"""
Provides a simple table class.  A SimpleTable is essentially
a list of lists plus some formatting functionality.

Dependencies: the Python 2.5+ standard library.

Installation: just copy this module into your working directory (or
   anywhere in your pythonpath).

Basic use::

   mydata = [[11,12],[21,22]]  # data MUST be 2-dimensional
   myheaders = [ "Column 1", "Column 2" ]
   mystubs = [ "Row 1", "Row 2" ]
   tbl = SimpleTable(mydata, myheaders, mystubs, title="Title")
   print( tbl )
   print( tbl.as_csv() )

A SimpleTable is inherently (but not rigidly) rectangular.
You should create it from a *rectangular* (2d!) iterable of data.
Each item in your rectangular iterable will become the data
of a single Cell.  In principle, items can be any object,
not just numbers and strings.  However, default conversion
during table production is by simple string interpolation.
(So you cannot have a tuple as a data item *and* rely on
the default conversion.)

A SimpleTable allows only one column (the first) of stubs at
initilization, concatenation of tables allows you to produce tables
with interior stubs.  (You can also assign the datatype 'stub' to the
cells in any column, or use ``insert_stubs``.) A SimpleTable can be
concatenated with another SimpleTable or extended by another
SimpleTable. ::

    table1.extend_right(table2)
    table1.extend(table2)


A SimpleTable can be initialized with `datatypes`: a list of ints that
provide indexes into `data_fmts` and `data_aligns`.  Each data cell is
assigned a datatype, which will control formatting.  If you do not
specify the `datatypes` list, it will be set to ``range(ncols)`` where
`ncols` is the number of columns in the data.  (I.e., cells in a
column have their own datatype.) This means that you can just specify
`data_fmts` without bothering to provide a `datatypes` list.  If
``len(datatypes)<ncols`` then datatype assignment will cycle across a
row.  E.g., if you provide 10 columns of data with ``datatypes=[0,1]``
then you will have 5 columns of datatype 0 and 5 columns of datatype
1, alternating.  Correspoding to this specification, you should provide
a list of two ``data_fmts`` and a list of two ``data_aligns``.

Cells can be assigned labels as their `datatype` attribute.
You can then provide a format for that lable.
Us the SimpleTable's `label_cells` method to do this.  ::

    def mylabeller(cell):
        if cell.data is np.nan:
            return 'missing'

    mytable.label_cells(mylabeller)
    print(mytable.as_text(missing='-'))


Potential problems for Python 3
-------------------------------

- Calls ``next`` instead of ``__next__``.
  The 2to3 tool should handle that no problem.
  (We will switch to the `next` function if 2.5 support is ever dropped.)
- Let me know if you find other problems.

:contact: alan dot isaac at gmail dot com
:requires: Python 2.5.1+
:note: current version
:note: HTML data format currently specifies tags
:todo: support a bit more of http://www.oasis-open.org/specs/tr9503.html
:todo: add labels2formatters method, that associates a cell formatter with a
       datatype
:todo: add colspan support to Cell
:since: 2008-12-21
:change: 2010-05-02 eliminate newlines that came before and after table
:change: 2010-05-06 add `label_cells` to `SimpleTable`
"""
def csv2st(csvfile, headers=..., stubs=..., title=...):
    """Return SimpleTable instance,
    created from the data in `csvfile`,
    which is in comma separated values format.
    The first row may contain headers: set headers=True.
    The first column may contain stubs: set stubs=True.
    Can also supply headers and stubs as tuples of strings.
    """
    ...

class SimpleTable(list):
    """Produce a simple ASCII, CSV, HTML, or LaTeX table from a
    *rectangular* (2d!) array of data, not necessarily numerical.
    Directly supports at most one header row,
    which should be the length of data[0].
    Directly supports at most one stubs column,
    which must be the length of data.
    (But see `insert_stubs` method.)
    See globals `default_txt_fmt`, `default_csv_fmt`, `default_html_fmt`,
    and `default_latex_fmt` for formatting options.

    Sample uses::

        mydata = [[11,12],[21,22]]  # data MUST be 2-dimensional
        myheaders = [ "Column 1", "Column 2" ]
        mystubs = [ "Row 1", "Row 2" ]
        tbl = text.SimpleTable(mydata, myheaders, mystubs, title="Title")
        print( tbl )
        print( tbl.as_html() )
        # set column specific data formatting
        tbl = text.SimpleTable(mydata, myheaders, mystubs,
            data_fmts=["%3.2f","%d"])
        print( tbl.as_csv() )
        with open('c:/temp/temp.tex','w') as fh:
            fh.write( tbl.as_latex_tabular() )
    """
    def __init__(self, data, headers=..., stubs=..., title=..., datatypes=..., csv_fmt=..., txt_fmt=..., ltx_fmt=..., html_fmt=..., celltype=..., rowtype=..., **fmt_dict) -> None:
        """
        Parameters
        ----------
        data : list of lists or 2d array (not matrix!)
            R rows by K columns of table elements
        headers : list (or tuple) of str
            sequence of K strings, one per header
        stubs : list (or tuple) of str
            sequence of R strings, one per stub
        title : str
            title of the table
        datatypes : list of int
            indexes to `data_fmts`
        txt_fmt : dict
            text formatting options
        ltx_fmt : dict
            latex formatting options
        csv_fmt : dict
            csv formatting options
        hmtl_fmt : dict
            hmtl formatting options
        celltype : class
            the cell class for the table (default: Cell)
        rowtype : class
            the row class for the table (default: Row)
        fmt_dict : dict
            general formatting options
        """
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self):
        ...
    
    def insert(self, idx, row, datatype=...):
        """Return None.  Insert a row into a table.
        """
        ...
    
    def insert_header_row(self, rownum, headers, dec_below=...):
        """Return None.  Insert a row of headers,
        where ``headers`` is a sequence of strings.
        (The strings may contain newlines, to indicated multiline headers.)
        """
        ...
    
    def insert_stubs(self, loc, stubs):
        """Return None.  Insert column of stubs at column `loc`.
        If there is a header row, it gets an empty cell.
        So ``len(stubs)`` should equal the number of non-header rows.
        """
        ...
    
    def pad(self, s, width, align):
        """DEPRECATED: just use the pad function"""
        ...
    
    def get_colwidths(self, output_format, **fmt_dict):
        """Return list, the widths of each column."""
        ...
    
    def as_csv(self, **fmt_dict):
        """Return string, the table in CSV format.
        Currently only supports comma separator."""
        ...
    
    def as_text(self, **fmt_dict):
        """Return string, the table as text."""
        ...
    
    def as_html(self, **fmt_dict):
        """Return string.
        This is the default formatter for HTML tables.
        An HTML table formatter must accept as arguments
        a table and a format dictionary.
        """
        ...
    
    def as_latex_tabular(self, center=..., **fmt_dict):
        '''Return string, the table as a LaTeX tabular environment.
        Note: will require the booktabs package.'''
        ...
    
    def extend_right(self, table):
        """Return None.
        Extend each row of `self` with corresponding row of `table`.
        Does **not** import formatting from ``table``.
        This generally makes sense only if the two tables have
        the same number of rows, but that is not enforced.
        :note: To extend append a table below, just use `extend`,
        which is the ordinary list method.  This generally makes sense
        only if the two tables have the same number of columns,
        but that is not enforced.
        """
        ...
    
    def label_cells(self, func):
        """Return None.  Labels cells based on `func`.
        If ``func(cell) is None`` then its datatype is
        not changed; otherwise it is set to ``func(cell)``.
        """
        ...
    
    @property
    def data(self):
        ...
    


def pad(s, width, align):
    """Return string padded with spaces,
    based on alignment parameter."""
    ...

class Row(list):
    """Provides a table row as a list of cells.
    A row can belong to a SimpleTable, but does not have to.
    """
    def __init__(self, seq, datatype=..., table=..., celltype=..., dec_below=..., **fmt_dict) -> None:
        """
        Parameters
        ----------
        seq : sequence of data or cells
        table : SimpleTable
        datatype : str ('data' or 'header')
        dec_below : str
          (e.g., 'header_dec_below' or 'row_dec_below')
          decoration tag, identifies the decoration to go below the row.
          (Decoration is repeated as needed for text formats.)
        """
        ...
    
    def add_format(self, output_format, **fmt_dict):
        """
        Return None. Adds row-instance specific formatting
        for the specified output format.
        Example: myrow.add_format('txt', row_dec_below='+-')
        """
        ...
    
    def insert_stub(self, loc, stub):
        """Return None.  Inserts a stub cell
        in the row at `loc`.
        """
        ...
    
    def get_aligns(self, output_format, **fmt_dict):
        """Return string, sequence of column alignments.
        Ensure comformable data_aligns in `fmt_dict`."""
        ...
    
    def as_string(self, output_format=..., **fmt_dict):
        """Return string: the formatted row.
        This is the default formatter for rows.
        Override this to get different formatting.
        A row formatter must accept as arguments
        a row (self) and an output format,
        one of ('html', 'txt', 'csv', 'latex').
        """
        ...
    
    @property
    def data(self):
        ...
    


class Cell(object):
    """Provides a table cell.
    A cell can belong to a Row, but does not have to.
    """
    def __init__(self, data=..., datatype=..., row=..., **fmt_dict) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def alignment(self, output_format, **fmt_dict):
        ...
    
    def format(self, width, output_format=..., **fmt_dict):
        """Return string.
        This is the default formatter for cells.
        Override this to get different formating.
        A cell formatter must accept as arguments
        a cell (self) and an output format,
        one of ('html', 'txt', 'csv', 'latex').
        It will generally respond to the datatype,
        one of (int, 'header', 'stub').
        """
        ...
    
    def get_datatype(self):
        ...
    
    def set_datatype(self, val):
        ...
    
    datatype = ...


default_txt_fmt = dict(fmt='txt', table_dec_above='=', table_dec_below='-', title_align='c', row_pre='', row_post='', header_dec_below='-', row_dec_below=None, colwidths=None, colsep=' ', data_aligns="r", data_fmts=["%s"], stub_align='l', header_align='c', header_fmt='%s', stub_fmt='%s', header='%s', stub='%s', empty_cell='', empty='', missing='--')
default_csv_fmt = dict(fmt='csv', table_dec_above=None, table_dec_below=None, row_pre='', row_post='', header_dec_below=None, row_dec_below=None, title_align='', data_aligns="l", colwidths=None, colsep=',', data_fmt='%s', data_fmts=['%s'], stub_align="l", header_align='c', header_fmt='"%s"', stub_fmt='"%s"', empty_cell='', header='%s', stub='%s', empty='', missing='--')
default_html_fmt = dict(table_dec_above=None, table_dec_below=None, header_dec_below=None, row_dec_below=None, title_align='c', colwidths=None, colsep=' ', row_pre='<tr>\n  ', row_post='\n</tr>', data_aligns="c", data_fmts=['<td>%s</td>'], data_fmt="<td>%s</td>", stub_align='l', header_align='c', header_fmt='<th>%s</th>', stub_fmt='<th>%s</th>', empty_cell='<td></td>', header='<th>%s</th>', stub='<th>%s</th>', empty='<td></td>', missing='<td>--</td>')
default_latex_fmt = dict(fmt='ltx', table_dec_above=r'\toprule', table_dec_below=r'\bottomrule', header_dec_below=r'\midrule', row_dec_below=None, strip_backslash=True, row_post=r'  \\', data_aligns='c', colwidths=None, colsep=' & ', data_fmts=['%s'], data_fmt='%s', stub_align='l', header_align='c', empty_align='l', header_fmt=r'\textbf{%s}', stub_fmt=r'\textbf{%s}', empty_cell='', header=r'\textbf{%s}', stub=r'\textbf{%s}', empty='', missing='--', replacements={ "#": r"\#","$": r"\$","%": r"\%","&": r"\&",">": r"$>$","_": r"\_","|": r"$|$" })
default_fmts = dict(html=default_html_fmt, txt=default_txt_fmt, latex=default_latex_fmt, csv=default_csv_fmt)
output_format_translations = dict(htm='html', text='txt', ltx='latex')
def get_output_format(output_format):
    ...

