"""
This type stub file was generated by pyright.
"""

from . import screen

'''This implements an ANSI (VT100) terminal emulator as a subclass of screen.

PEXPECT LICENSE

    This license is approved by the OSI and FSF as GPL-compatible.
        http://opensource.org/licenses/isc-license.txt

    Copyright (c) 2012, Noah Spurrier <noah@noah.org>
    PERMISSION TO USE, COPY, MODIFY, AND/OR DISTRIBUTE THIS SOFTWARE FOR ANY
    PURPOSE WITH OR WITHOUT FEE IS HEREBY GRANTED, PROVIDED THAT THE ABOVE
    COPYRIGHT NOTICE AND THIS PERMISSION NOTICE APPEAR IN ALL COPIES.
    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

'''
def DoEmit(fsm):
    ...

def DoStartNumber(fsm):
    ...

def DoBuildNumber(fsm):
    ...

def DoBackOne(fsm):
    ...

def DoBack(fsm):
    ...

def DoDownOne(fsm):
    ...

def DoDown(fsm):
    ...

def DoForwardOne(fsm):
    ...

def DoForward(fsm):
    ...

def DoUpReverse(fsm):
    ...

def DoUpOne(fsm):
    ...

def DoUp(fsm):
    ...

def DoHome(fsm):
    ...

def DoHomeOrigin(fsm):
    ...

def DoEraseDown(fsm):
    ...

def DoErase(fsm):
    ...

def DoEraseEndOfLine(fsm):
    ...

def DoEraseLine(fsm):
    ...

def DoEnableScroll(fsm):
    ...

def DoCursorSave(fsm):
    ...

def DoCursorRestore(fsm):
    ...

def DoScrollRegion(fsm):
    ...

def DoMode(fsm):
    ...

def DoLog(fsm):
    ...

class term(screen.screen):
    '''This class is an abstract, generic terminal.
    This does nothing. This is a placeholder that
    provides a common base class for other terminals
    such as an ANSI terminal. '''
    def __init__(self, r=..., c=..., *args, **kwargs) -> None:
        ...
    


class ANSI(term):
    '''This class implements an ANSI (VT100) terminal.
    It is a stream filter that recognizes ANSI terminal
    escape sequences and maintains the state of a screen object. '''
    def __init__(self, r=..., c=..., *args, **kwargs) -> None:
        ...
    
    def process(self, c):
        """Process a single character. Called by :meth:`write`."""
        ...
    
    def process_list(self, l):
        ...
    
    def write(self, s):
        """Process text, writing it to the virtual screen while handling
        ANSI escape codes.
        """
        ...
    
    def flush(self):
        ...
    
    def write_ch(self, ch):
        '''This puts a character at the current cursor position. The cursor
        position is moved forward with wrap-around, but no scrolling is done if
        the cursor hits the lower-right corner of the screen. '''
        ...
    
    def do_sgr(self, fsm):
        '''Select Graphic Rendition, e.g. color. '''
        ...
    
    def do_decsca(self, fsm):
        '''Select character protection attribute. '''
        ...
    
    def do_modecrap(self, fsm):
        '''Handler for \x1b[?<number>h and \x1b[?<number>l. If anyone
        wanted to actually use these, they'd need to add more states to the
        FSM rather than just improve or override this method. '''
        ...
    


