"""
This type stub file was generated by pyright.
"""

from pymoo.model.termination import Termination

class TimeBasedTermination(Termination):
    def __init__(self, max_time) -> None:
        ...
    
    def do_continue(self, algorithm):
        ...
    


