"""
This type stub file was generated by pyright.
"""

from pymoo.model.termination import Termination

class MaximumGenerationTermination(Termination):
    def __init__(self, n_max_gen) -> None:
        ...
    


